"""
Run visual question answering on EXAMS-V dataset using Qwen2.5-VL-72B-Instruct model.

This script loads images and metadata from a dataset JSON file, generates answers
to visual multiple-choice questions using a vision-language model, extracts the
predicted answer labels (A-E), and saves the results to an output JSON.

Features:
- Loads a 4-bit quantized Qwen2.5-VL-72B-Instruct model for memory-efficient inference.
- Processes images and constructs detailed prompts.
- Extracts clean answers even from verbose model outputs.
- Frees GPU memory after each prediction to avoid OOM errors.

Usage:
    python3 final.py

"""

import json
import torch
from PIL import Image
from transformers import Qwen2_5_VLForConditionalGeneration, AutoTokenizer, AutoProcessor, BitsAndBytesConfig
from qwen_vl_utils import process_vision_info
import re

def extract_answer(response_text):
    """
    Extract the final answer label (A-E) from a model-generated response.

    Handles various response patterns like "Answer: A", "I choose B", "C.", etc.

    Args:
        response_text (str): The raw text generated by the model.

    Returns:
        str: Extracted answer label ('A', 'B', 'C', 'D', or 'E'). Defaults to 'A' if none found.
    """
    response_text = response_text.strip()
    
    # Direct match
    if response_text in ['A', 'B', 'C', 'D', 'E']:
        return response_text

    # Try various regex patterns
    patterns = [
        r'(?:answer|option|choice)(?:\s+is)?\s*[:\-]?\s*([A-E])\b',
        r'\b([A-E])\b(?:\s+is(?:\s+the)?(?:\s+correct)?\s+(?:answer|option|choice))',
        r'(?:I|the|my)(?:\s+(?:answer|choose|select|pick|opt|go|think))(?:\s+(?:is|for|with))?\s*[:\-]?\s*([A-E])\b',
        r'\b([A-E])\.',  # Single letter followed by a period
    ]

    for pattern in patterns:
        match = re.search(pattern, response_text, re.IGNORECASE)
        if match:
            return match.group(1).upper()

    # Fallbacks: any single A-E match
    matches = re.findall(r'\b([A-E])\b', response_text)
    if matches:
        return matches[0].upper()

    # Last fallback: any character match
    for char in response_text:
        if char in ['A', 'B', 'C', 'D', 'E']:
            return char

    return "A"  # Default if no answer found

# Configurations
INPUT_FILE = "exams_v_test_full_with_paths.json"
OUTPUT_FILE = "run.json"

# Create BitsAndBytesConfig for efficient 4-bit quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,            # Enable 4-bit quantization to save memory and speed up inference
    compute_dtype=torch.bfloat16  # Use bfloat16 for computation to balance performance and precision
)

# Load the Qwen2.5-VL-72B-Instruct model with quantization
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-72B-Instruct",  # Model identifier from HuggingFace Hub
    torch_dtype=torch.bfloat16,      # Set model computation to bfloat16 precision
    device_map="auto",               # Automatically distribute model across available devices (e.g., multiple GPUs / CPU fallback)
    quantization_config=bnb_config   # Apply the BitsAndBytes quantization config for 4-bit loading
)

# Load the processor (tokenizer + feature extractor for vision)
processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen2.5-VL-72B-Instruct",  # Processor checkpoint (should match model)
    use_fast=True                    # Use the "fast" tokenizer backend (built with Rust for speed)
)

# Load input dataset
with open(INPUT_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

results = []

# Process each example
for item in data["rows"]:
    row = item["row"]
    image_path = row["image"]["path"]
    sample_id = row["sample_id"]
    language = row["language"]
    subject = row["subject"]
    grade = row["grade"]

    try:
        # Load and prepare the image
        image = Image.open(image_path).convert("RGB")

        # Build the prompt
        prompt = (
            f"You are an expert in solving visual multiple-choice exam questions. "
            f"This is an exam question in {language} for Grade {grade} {subject}.\n\n"
            f"Step 1: Carefully extract the question and all answer options (labeled A, B, C, ...), regardless of language.\n"
            f"Step 2: Analyze any diagrams, graphs, tables, or visual content.\n"
            f"Step 3: Reason through the question and choose the best option.\n"
            f"Step 4: Only return the label of the correct option (A, B, C, etc). Do not explain.\n"
            f"Image is provided below.\n"
        )

        # Prepare input messages for the model
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": prompt},
                ],
            }
        ]

        # Encode inputs using processor
        text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        # Prepare visual inputs for the processor:
        # - 'process_vision_info' extracts images/videos properly formatted for the model.
        image_inputs, video_inputs = process_vision_info(messages)

        # Tokenize and encode the multimodal input (text + image):
        inputs = processor(
            text=[text],               # List of input texts (only one here, wrapped in a list)
            images=image_inputs,        # List of image tensors extracted from the message
            videos=video_inputs,        # (Empty in our case — no videos — but processor expects it)
            padding=True,               # Pad inputs to have the same length across the batch
            return_tensors="pt",        # Return PyTorch tensors
        ).to("cuda")                    # Move inputs to GPU for faster inference

        # Run inference (generation) without tracking gradients to save memory:
        with torch.no_grad():
            generated_ids = model.generate(
                **inputs,
                max_new_tokens=256       # Limit the number of tokens the model can generate
            )

            # Decode the generated token IDs back into human-readable text
            response = processor.batch_decode(
                generated_ids,
                skip_special_tokens=True # Remove special tokens like <|endoftext|>
            )
            text = response[0]  # Extract the single response from the batch

            # Post-process the generated text:
            # Try to find where the 'assistant' token ends and extract the response after it
            last_assistant_index = text.rfind("assistant")
            if last_assistant_index != -1:
                response = text[last_assistant_index + len("assistant"):].strip()
            else:
                response = text.strip()  # Fallback if 'assistant' not found

            # Extract the clean answer label (A-E) from the response
            clean_response = extract_answer(response)

            # Print the prediction
            print(f"id : {sample_id}\nlanguage : {language}\nanswer_key : {clean_response}\n")

            # Save the result
            results.append({
                "id": sample_id,
                "answer_key": clean_response,
                "language": language,
            })

        # Clean up per sample
        del inputs, generated_ids, response, image_inputs, video_inputs
        torch.cuda.empty_cache()

    except Exception as e:
        print(f" Error processing {sample_id}: {e}")

# Save all predictions to output file
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(results, f, indent=2)

print(f" Saved {len(results)} predictions to {OUTPUT_FILE}")
